######################################################################
# Automatically generated by qmake (2.01a) Sun Dec 21 21:50:42 2008
######################################################################
TEMPLATE = subdirs
CONFIG  += ordered
SUBDIRS = core \
          gui \
          wall
