######################################################################
# Automatically generated by qmake (2.01a) Sun Dec 14 00:50:36 2008
######################################################################

TEMPLATE = lib
TARGET = QTabletGui
DEPENDPATH += .
INCLUDEPATH += .
CONFIG += dll

# Input
HEADERS += pannableview.hh
SOURCES += pannableview.cc
