######################################################################
# Automatically generated by qmake (2.01a) Mon Dec 8 00:15:39 2008
######################################################################

include(../3rdparty/qtanimationframework-1.0-opensource/src/qtanimationframework.pri)

TEMPLATE = app
TARGET =  qtabletwall
DEPENDPATH += .
INCLUDEPATH += . ../gui
LIBS += -L../gui -lQTabletGui

# Input
#HEADERS += 
SOURCES += main.cc 
